# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20170329_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
